// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgwiqV9JmqOGlRyd6qa12372fPlzxr1ek',
    appId: '1:890258382242:android:f95f9257bdf713cf5f66fb',
    messagingSenderId: '890258382242',
    projectId: 'wedding-invite-56754',
    storageBucket: 'wedding-invite-56754.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACyAXqan1wN31PoSW_ItqZ49_99E-0tbo',
    appId: '1:890258382242:ios:ba4f0c763538297c5f66fb',
    messagingSenderId: '890258382242',
    projectId: 'wedding-invite-56754',
    storageBucket: 'wedding-invite-56754.firebasestorage.app',
    androidClientId: '890258382242-15fpg7oqrbk5qtg1rl6nmitbteh2dmgl.apps.googleusercontent.com',
    iosClientId: '890258382242-an4e83t7ta0hd0u2mg7gais2656s486b.apps.googleusercontent.com',
    iosBundleId: 'com.fogtheagency.otl',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdIxIg5d-7VbpsXsW3kXXjv7wvKKQzJ0I',
    appId: '1:890258382242:web:19027909f209e90b5f66fb',
    messagingSenderId: '890258382242',
    projectId: 'wedding-invite-56754',
    authDomain: 'wedding-invite-56754.firebaseapp.com',
    storageBucket: 'wedding-invite-56754.firebasestorage.app',
    measurementId: 'G-SFTQSXYT4D',
  );

}